[package]
name = "actix-web-admin"
version = "0.1.0"
authors = ["辰浦枫 <15227171200@139.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
